README.md

Add warning in readme

---

lib/proxy.coffee
views/layout.horizonal.cjsx
views/layout.vertical.cjsx

Fix https://github.com/yudachi/poi/issues/16

Fix layout change

---

plugins/item-info/env.coffee
plugins/item-info/views/index.cjsx
plugins/ship-info/env.coffee
plugins/ship-info/views/ship-info-table-area.cjsx
views/components/main/parts/teitoku-panel.cjsx
views/env.coffee

Add plugin ownedlist

---

default-config.json
index.html
lib/proxy.coffee
views/env.coffee
views/layout.horizonal.cjsx
views/layout.vertical.cjsx

API CHANGE
_ships extends $ships
FIX
payitem zoom
layout change event
env.coffee [ready to embeed to plugins]

Add _ships.[$ships.keys]. Fix payitem. Fix window layout. Fix env

---

app.coffee
gulpfile.coffee
index.html
lib/window.coffee
views/components/settings/parts/navigator-bar.cjsx
views/layout.horizonal.cjsx
views/layout.vertical.cjsx

Fix adjust

---

README.md
docs/plugin-cn.md
views/components/main/parts/ndock-panel.cjsx
views/components/main/parts/teitoku-panel.cjsx
views/components/settings/parts/plugin-config.cjsx
views/components/ship/index.cjsx
views/components/ship/parts/slotitems.cjsx
views/env.coffee

After this PR, _ships and _slotitems are both Object. No _.sortedIndex!

Change _slotitems, _ships api

---

package.json
views/env.coffee

Fix win notify, Fix https://github.com/yudachi/poi/issues/62

---

views/components/main/parts/task-panel.cjsx

task-panel state also keeps track of task category and type
task-panel dispatches "task.change" events when it updates its state
task-panel listens to "task.info" events and updates its state

add quest plugin support

---

lib/utils.coffee

screenshot addition

---

views/app.cjsx

This pr adds an icon for opening dev tools of poi main window.

Add dev tools icon

---

assets/css/app.css
views/app.cjsx

This pr adds an icon for setting main window always on top.

Add always on top

---

views/components/settings/parts/poi-config.cjsx

……清理缓存失败的时候，自动打开缓存目录
……依葫芦画瓢写的，Windows 下测试可行

Open cache dir automatically when clear cache failed

---

views/app.cjsx

Fix https://github.com/yudachi/poi/issues/95

Save config for muted and always on top

---

assets/css/app.css
views/components/ship/index.cjsx

Fix https://github.com/yudachi/poi/issues/111

Fix bug when changing ship

---

views/components/settings/parts/others.cjsx

add new contributor

---

app.coffee

Fix OSX clipboard

---

app.coffee
index.html
lib/window.coffee
views/env.coffee

Fix navigating on drop file or elements on window.

Disable navigate on drop

---

default-config.json
views/components/settings/parts/poi-config.cjsx
views/double-tabareas.cjsx
views/env.coffee
views/layout.horizonal.cjsx
views/layout.vertical.cjsx

+ Add fixed webview width to vertical layout
+ Rewrite fixed width settings

Scale to width

---

views/components/main/parts/teitoku-panel.cjsx

update shipcount in battle

---

views/components/ship/index.cjsx

using setState
扔桶时刷新shipview血条

refresh hp when speedup repair

---

views/components/main/index.cjsx
views/components/settings/index.cjsx
views/components/ship/index.cjsx
views/components/ship/parts/index.cjsx
views/components/ship/parts/panebody.cjsx
views/double-tabareas.cjsx
views/single-tabarea.cjsx

Revert "Revert "speed up tab-switch""

---

views/components/main/index.cjsx
views/components/settings/index.cjsx
views/components/ship/index.cjsx
views/components/ship/parts/panebody.cjsx
views/double-tabareas.cjsx
views/single-tabarea.cjsx

Speedup tab switch

---

views/components/main/parts/task-panel.cjsx

rePr fix colors

---

views/components/ship/parts/panebody.cjsx

enhancement: 按照倒计时自动刷新cond
fix: 移除低cond船时清零计时器

update cond dynamically

---

views/components/main/parts/teitoku-panel.cjsx
views/components/ship/index.cjsx
views/components/ship/parts/panebody.cjsx
views/env.coffee

fix resource and reorder path

---

views/components/main/parts/kdock-panel.cjsx
views/components/main/parts/mission-panel.cjsx
views/components/main/parts/ndock-panel.cjsx
views/components/ship/parts/panebody.cjsx
views/env.coffee

增加通知的配置
* 兼容原本的通知设置（开关通知声音）
* 增加开关通知的选项
* 增加单独开关每种类型的通知（建造、修理、远征、疲劳度），默认都为开
* 允许对每种通知设置不同的提示音
TODO：
实际的设置界面还没做（UI 苦手）
config 中的选项等写 config 文档的时候说明。

Enhance notification

---

views/env.coffee

修复关闭通知时还会播放通知提示音的问题
刚进浴室洗澡就发现这个 bug...

Fix: Play sound when notification disabled

---

views/components/main/parts/teitoku-panel.cjsx

fix the exp of lv.120

---

views/components/settings/parts/poi-config.cjsx

增加开启/关闭通知及其声音的选项。
详细设置有心情再说了...

Setting view for enable/disable notification

---

lib/window.coffee
views/layout.cjsx

This pr makes poi capture charging window to native brower-window.

Capture charge page

---

README.md

https://github.com/yudachi/poi/pull/109#issuecomment-117436081 所提到的秘书舰语音通知。

Add plugin: secretary

---

views/components/main/parts/mission-panel.cjsx
views/components/main/parts/ndock-panel.cjsx

add OverlayTrigger in mission-panel and ndock-panel

Add complete time

---

views/battle_env.coffee

It need to add api_color_no to help judge if we are fighting with the boss.
In fact, we may only need to use api_color_no to judge it. Maybe there are some misunderstanding about the api_bosscell_no and api_no.
But I am sure that now these codes are right.

fix boss judgement

---

views/components/main/parts/teitoku-panel.cjsx

using status bar instead of modal
**may be instable cos setTimeout**

Add ship full alert

---

assets/data/quest_goal.cson
views/components/main/parts/task-panel.cjsx

Fix https://github.com/poooi/poi/issues/204 .

Sync quest progress with game

---

views/components/settings/parts/poi-config.cjsx

fix max item alert

---

views/components/ship/parts/panebody.cjsx

add overlay tips of repair time on hp-progress

add overlay tips of repair time on hp-progress

---

views/components/settings/parts/poi-config.cjsx
views/env.coffee

Offer notification sound volume setting instead of on/off.

---

views/components/settings/parts/poi-config.cjsx
views/env.coffee

Reverts poooi/poi#222
Toooooooooooo ugly oh my god.

Revert "Offer notification sound volume setting instead of on/off."

---

views/components/settings/assets/settings.css
views/components/settings/parts/poi-config.cjsx

重构后的通知音量条
主题适配似乎 @PHELiOX 正在做、晚些和他沟通一下

Notification setting: show volume as tooltip

---

views/env.coffee

噫... `env.coffee` 的通知音量之前被 revert 了完全不知道...

Play notification sound with volume. (Recover from #222)

---

views/components/ship/ship.cjsx

This PR ignores warning when a heavy damaged ship had come back.

Add goback support

---

lib/proxy.coffee

Fix https://github.com/poooi/poi/issues/248 .

Add retry for 503

---

views/app.cjsx

Add
Linux/Windows: F5 / Ctrl+F5
MacOS: Cmd+R / Cmd+Shift+R
Fix https://github.com/poooi/poi/issues/246 .

Add refresh shortkey

---

views/app.cjsx

Right click 'open cache folder' button to access 'cache/kcs/resources/swf/ships'.

Add shortcut to makai folder

---

i18n/ja-JP.json
i18n/zh-CN.json
i18n/zh-TW.json
views/app.cjsx

Change i18n text (en-US) of map reminder.

---

views/components/ship/assets/ship.css

Because of fifth slotitem, we might make the slotitem smaller.

Smaller slotitem

---

assets/data/quest_goal.cson
views/components/main/parts/task-panel.cjsx

> Operation A-gou:
Launch your fleet 36 times, encounter 24 bosses, kill 12 bosses, and get 6 S-Rank victories.
Not battle 36 times.

Fix A-gou quest

---

assets/css/app.css

Made bold yellow less bright.
Made gold slightly brighter.

Slightly adjusted color

---

i18n/en-US.json
i18n/ja-JP.json
i18n/zh-CN.json
i18n/zh-TW.json
views/components/main/parts/task-panel.cjsx

Added HeadquartersPersonnel indication to i18n and lockedTask. Tested.

---

views/components/main/parts/resource-panel.cjsx

Show shadow when resourse under limit

---

i18n/en-US.json
i18n/ja-JP.json
i18n/zh-CN.json
i18n/zh-TW.json

i18n for #399

---

views/components/settings/parts/navigator-bar.cjsx

Address-bar Improvement

---

views/app.cjsx

Fix overriding varable

---

views/components/main/parts/teitoku-panel.cjsx

原来是要鼠标指到提督等级上才会显示经验，很难发现，所以改成了指提督名也显示。
另外还有一些细微的显示改动。。

Minor changes to how admiral exp is displayed.

---

views/components/main/parts/miniship.cjsx

Double click to toggle between miniship view and ship wiew.

---

i18n/en-US.json
i18n/ja-JP.json
i18n/zh-CN.json
i18n/zh-TW.json
views/app.cjsx

Fix https://github.com/poooi/poi/issues/420

Fix 'Waiting Response...'

---

views/components/main/parts/miniship-parts/panebody.cjsx

Use the global method. So the custom css can apply.

Fixed cond

---

views/env.coffee

Fix parse error

---

views/single-tabarea.cjsx

Fixed plugin shortcut keys for single-tabarea

---

views/double-tabareas.cjsx

Fixed plugin shortcut keys for double tabarea

---

constant.cson
views/app.cjsx
views/components/settings/parts/navigator-bar.cjsx

右击刷新按钮，或者 alt+f5(cmd+alt+r) 时，只刷新 flash（token 不变）而不刷新整个页面。
用于演习SL的隐藏功能

refresh without changing token

---

constant.cson

Add contributor yukixz

---

views/components/main/parts/kdock-panel.cjsx

Provided a way to delay the item development result

---

views/double-tabareas.cjsx
views/single-tabarea.cjsx

Bugfix  tab switches when opening new window plugin

---

views/env.coffee

Fix localStorage.start2Version

---

views/layout.vertical.cjsx

It performed well in Win8.1 x64, and need to be tested in Mac & Linux.

Fix auto-adjustment bug in vertical-layout

---

views/layout.vertical.cjsx

这回大概没问题了（扶额
不过是指标不治本的解决手段…webview那个奇怪的问题没能解决。但起码纵版自适应后不会出现白边了。

Add padding-right in vertical-layout to adjust

---

views/components/main/parts/miniship.cjsx
views/env.coffee

Slot exchange api and preset_select api

Add new apis and update dependencies

---

views/components/settings/parts/poi-config.cjsx

fix screenshot path

---

views/components/settings/parts/poi-config.cjsx

hotfix screenshot path

---

views/components/main/parts/miniship-parts/minipanebody.cjsx
views/components/main/parts/miniship-parts/slotitems.cjsx

minor ui improvement

---

views/app.cjsx

不要在意把 suppress 拼成了 supress   = 。=

supress css error

---

app.coffee

终于能统一了，开心
问题就是下次更新的时候，windows用户原先的配置文件会失效 TAT

change win32 EXROOT

---

views/components/main/parts/miniship-parts/statuslabel.cjsx

Update ship tag to 2015 autumn event

---

views/app.cjsx
views/env.coffee

Handle event map rank

---

assets/css/app.css

fix poi config's bottom margin

minor UI fix

---

views/components/main/parts/kdock-panel.cjsx
views/components/main/parts/miniship-parts/topalert.cjsx
views/components/main/parts/mission-panel.cjsx
views/components/main/parts/ndock-panel.cjsx
views/env.coffee

修改后的标题和内容：
API 兼容。标题默认为 `poi`。
For https://github.com/poooi/poi/issues/543
~~咦、好像可以改进一下文字描述。~~

通知允许设置标题 && Win8 以上使用 Notification API

---

views/components/settings/parts/navigator-bar.cjsx

Usage: right click "Set HomePage".

Add feature: goto homepage

---

package.json
views/update.cjsx

#520 
改动了 dependency，建议在 5.0.0 的时候 merge

suppress update notice

---

views/components/main/parts/miniship-parts/statuslabel.cjsx

1. Simply code
2. E1, E2, E3 => bsStyle: success(green)
E4 => bsStyle: warning(yellow)

Status label refactor

---

views/components/settings/parts/poi-config.cjsx
views/env.coffee

有个彩蛋(bug)：在其他地方按下鼠标、然后移动到通知音量部分松开、也有通知音。

Play sound on set notification volume

---

i18n/ja-JP.json
i18n/zh-CN.json
i18n/zh-TW.json
views/components/settings/parts/poi-config.cjsx
views/layout.cjsx

Add option to disable DMM's network change alert

---

views/components/settings/parts/plugin-config.cjsx
views/components/settings/parts/poi-config.cjsx

Support to check beta plugins

---

views/components/settings/parts/plugin-config.cjsx

Fix update halt when plugin's latest isnt on npmjs

---

views/components/main/assets/ship.css
views/components/main/parts/miniship.cjsx

从来没点过这两个按钮，感觉不是很有必要的样子。
你们觉得这按钮有用的话，我就用我的 fork 去吧~ ~

remove button

---

views/components/main/parts/miniship-parts/panebody.cjsx

原本要鼠标指到血条上才会显示维修时间，血条变细之后就一直不太好指，所以将显示tooltip的区域稍微增大，以及tooltip移到右边

Made easier to show the repair time

---

i18n/others/en-US.json
i18n/others/ja-JP.json
i18n/others/zh-CN.json
i18n/others/zh-TW.json
views/services.coffee
views/services/modernization-delta.coffee

- Controlled by hidden config ``feature.modernization-delta.enable``
- Untested: 
- Hidden config 
- Luck modernization

Feature modernization-delta.

---

assets/data/plugin.json

poi-plugin-expedition 的 i18n 没有写，因为插件自己还没有做对应的 i18n。

Update i18n and NTR information

---

views/components/settings/parts/poi-config.cjsx

Now class ``PoiConfig`` looks much prettier. Also, the two folder pickers no longer use duplicate code.

Extracted terms in poi-config to separate classes.

---

lib/window.coffee

Fixed black screen when close a window in fullscreen mode

---

build_detail.coffee

Use npm pack to generate plugin offline tarballs

---

lib/proxy.coffee
views/env.coffee

According to the heap snapshots taken with poi-plugin-akashic-records, it can reduce 40% memory leak.
Related to #676

Decrease memory leak

---

views/services/welcome.cjsx

Fixed wrong DOM nesting warning

---

views/components/main/assets/main.css
views/components/main/parts/miniship.cjsx
views/components/main/parts/resource-panel.cjsx

Adjust panel margin

---

build_detail.coffee
gulpfile.coffee
package.json

Build script enhancement

---

.travis.yml
build_detail.coffee

Tests ``gulp install`` ``gulp build`` ``gulp build_plugins`` in travisci . 
The environment is linux.
No idea what it means though.

Passes travis.ci building.

---

views/components/main/parts/kdock-panel.cjsx
views/components/main/parts/ndock-panel.cjsx

绿色与灰色相间的 bug 可能是由于 countdown 直接降到 -1 导致的？
由于我没法重现这个问题，所以只是猜测 = =
~~好讨厌重复代码  这个函数怎么样才能共用啊……~~

fix countdown

---

lib/ipc.coffee

register
call
注册、调用即可。
可以使用 callback，callback 的 this 指针会指歪。

Inter-Plugins Call module.

---

views/components/main/parts/mission-panel.cjsx
views/components/main/parts/ndock-panel.cjsx
views/env.coffee

Use a more natural time format

---

views/components/main/parts/kdock-panel.cjsx
views/components/main/parts/mission-panel.cjsx
views/components/main/parts/ndock-panel.cjsx

Which potentially can cause memory leak and waste of CPU

Fixed misuse of clearInterval()

---

lib/ipc.coffee

[5.1.0] Add Inter-Plugins Call module.

---

assets/css/app.css
views/single-tabarea.cjsx

https://github.com/poooi/poi/issues/706

Plugin nav split improve

---

lib/utils.coffee

Remove use of colors for now

---

views/services/modernization-delta.coffee

- Fixed judgment on max.
- Added remainingStatus display.
#703

Rewrote modernization-delta.

---

views/env.coffee

It will cause network error if we don't remove these listenters when we reload new-window-type plugins.

Patch env about proxy listener

---

lib/ipc.coffee

Add IPC API: foreach

---

views/env.coffee

Bug fix: load event doesnt dispatch after DOM loaded

---

views/services/modernization-delta.coffee

To ``++``, ``+``, and ``/remaining``

Change modernization-delta format

---

assets/css/app.css

disable input[number]::spin

---

docs/plugin-cn.md
docs/plugin.md

Plugin developing guide translated.
Considering the rapid development of poi, the English version may only be updated with every major release.

Plugin dev guide in English

---

docs/README.md

update readme for eng dev guide link

---

views/services/layout.vertical.cjsx

Add min vertical poi-panel height

---

views/env.coffee

Fix multiple issue caused by notification api on windows.

---

views/components/main/assets/main.css
views/components/main/parts/resource-panel.cjsx

grow -> glow

---

lib/proxy.coffee
views/app.cjsx

Set proxy status & Check it

---

assets/css/app.css
views/components/info/map-reminder.cjsx

Show event map hp

---

assets/css/app.css
views/components/settings/assets/settings.css
views/components/settings/parts/plugin-config.cjsx

- Extract ``InstalledPlugin`` and ``UninstalledPlugin``
- Replace inline css styles with classes.
- Correct the usage of layout elements (``Row`` and ``Col``).

Refactor plugin setting

---

views/components/settings/parts/display-config.cjsx

- Fixed the problem where resolution limit is ineffective
- Resolution limit is now affected by zoom level

Fixed resolution limit 

---

app.coffee
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
lib/proxy.coffee
package.json
views/components/settings/parts/network-config.cjsx

Test with: https://super.crystalacg.com/proxy_ssl.pac
May have bug with socks proxy.
Allow proxy type `PROXY`, `HTTPS`, `SOCKS` only.

Pac setting

---

views/components/main/parts/miniship.cjsx
views/components/ship-parts/minipanebody.cjsx
views/components/ship-parts/panebody.cjsx
views/components/ship/index.cjsx

Remove handleResponse of MiniShip and accept data from ShipView

Shipview multiplex

---

assets/data/constant.cson
assets/data/plugin.json

Add Where's My Fuel Gone plugin. Add DKWings contributor.

---

docs/plugin-cn.md
docs/plugin.md
lib/ipc.coffee

* Rename `ipc.foreach` to `ipc.foreachCall`.
* Update docs (zh&en) for IPC.

Update docs for IPC

---

views/components/main/parts/miniship.cjsx
views/components/ship-parts/minipanebody.cjsx
views/components/ship-parts/panebody.cjsx
views/components/ship/index.cjsx

Fix https://github.com/poooi/poi/issues/786

Reject render of panebody when no available data

---

lib/proxy.coffee

Consider more files as static files

---

app.coffee

This checks all available displays.

Check saved main window position before create it

---

build_detail.coffee
pack_osx.sh

Fix two problems of build script

---

views/app.cjsx

click appicon to show window

---

views/components/main/parts/mission-panel.cjsx

Show the completed times of all missions (including the finished missions).
Someone requested this change.

Show all missions' completed times

---

views/services.coffee

fix issue#831

---

assets/data/quest_goal.cson
views/components/main/parts/task-panel.cjsx

Fix issue#780

---

docs/plugin-cn.md
lib/window.coffee
views/components/settings/parts/plugin-config.cjsx
views/env.coffee
views/services/plugin-manager.cjsx
views/tabarea.cjsx

Fix #855 #864 #865 #866 #868 #869

Plugin rework

---

views/components/ship/index.cjsx

listen to remodeling

---

views/app.cjsx
views/components/settings/parts/display-config.cjsx
views/services/layout.cjsx

A better solution for https://github.com/poooi/poi/pull/845

Set zoom level by append css

---

views/services/layout.cjsx

Fix layout bug caused by undefined factor

---

views/services/layout.cjsx

Correct unfixed resolution

---

app.coffee
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/poi-config.cjsx

Fix https://github.com/poooi/poi/issues/908

Add a option to disable creating shortcut

---

i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/network-config.cjsx

local port -> poi port

---

assets/css/app.css
i18n/setting/en-US.json
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/main/assets/miniship.css
views/components/main/parts/miniship.cjsx
views/components/settings/parts/display-config.cjsx
views/components/ship/assets/ship.css
views/components/ship/index.cjsx
views/tabarea.cjsx

Add config about transition effect

---

lib/proxy.coffee
views/env-parts/data-resolver.coffee

Clear game-specific code out from proxy to app

---

pack_osx.sh

tidy up pack_osx.sh by a bit

---

i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/poi-config.cjsx
views/services.coffee

Close https://github.com/poooi/poi/issues/935

Add option to disable network status log

---

views/services/modernization-delta.coffee

Change remaining == 0 / != 0 to <= 0 / > 0 due to game bug

---

views/components/etc/icon.cjsx

1. fix 'undefined' in className when `@props.className` does not exist
2. only fallback in `slotItemIcon` instead of `materialIcon`

fix slotitem icon

---

views/services/plugin-manager.cjsx

Set NPM config progress=false

---

app.coffee

It should have effects only for git version.

set window icon and default title

---

lib/proxy.coffee
views/env-parts/data-resolver.coffee

Add server IP

---

assets/data/plugin.json

Update plugin: battle detail

---

.eslintrc.js
package.json

**请讨论达成共识后再磨叽**
因为关系到代码风格问题
启用规则：
1. 使用了 eslint & eslint-react 推荐规则。
2. 对 console.warn/error 之外的 console 调用报 warning。
3. 对未使用变量报 warning（函数参数除外）。
推荐规则（没启用）：
~~稍后更新~~

Add eslint

---

package.json
views/redux/battle.es

`"{"rank":"A","boss":true,"map":11,"deckShipId":[431],"deckHp":[7],"enemyShipId":[505,501,501,-1,-1,-1],"enemyHp":[-4,20,-26,-1,-1,-1]}"`
不知道怎么动 `create-store`

Using poi-lib-battle

---

views/redux/info/airbase.es
views/utils/tools.es

Fix: New air base API

---

assets/css/app.css
assets/data/plugin.json
docs/plugin-cn.md
docs/plugin.md
lib/proxy.es
lib/window.es
package.json
views/components/info/map-reminder.es
views/components/main/parts/miniship.es
views/components/ship/index.es
views/services.es
views/tabarea.es
views/utils/game-utils.es

English translations for plugin dev doc

Make Poi Document Great Again!

---

assets/data/fcd/meta.json
assets/data/fcd/shiptag.json
fcd/shiptag.cson
views/components/ship-parts/statuslabel.es
views/utils/game-utils.es

use HTML hex color for event tag

---

docs/plugin-cn.md
docs/plugin.md
views/redux/battle.es

Add start time to @@BattleResult 

---

i18n/main/ja-JP.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/components/main/assets/miniship.css
views/components/ship-parts/topalert.es
views/components/ship/assets/ship.css
views/components/ship/shipitem.es
views/utils/game-utils.es

- remove lv sum in miniship
- add speed indicator for fleet
- add speed information for ship

Add speed indicators #1306

---

assets/data/plugin.json

fix typos and some kind of translation clarification.

---

assets/js/webview-preload.js

This is a temperoary fix for #1230 before the upstream fix is finally landed
tested with Electron 1.5.0 beta Windows 10 x64 with and without ShimakazeGo

better align method

---

assets/data/quest_goal.cson
views/redux/info/quests.es

add new quest goals
638/F34 対空機銃量産 ( relative reducer updated)
822/Bq1 沖ノ島海域迎撃戦

Quest goal renew

---

package.json

Prevent build with non-tested electron

---

build_detail.es
gulpfile.js

They're so smart, awesome, and will make poi great again

camelCase variable is good civilization

---

docs/README.md
docs/style-guide-cn.md
docs/style-guide.md

RT.
Any suggestions and corrections are welcome

Add poi code style guide to docs

---

README.md

Change https://github.com/dazzyd to https://github.com/yukixz

Fix inconsistent author Url for Dazzy Ding

---

views/components/main/index.es
views/components/main/parts/miniship.es
views/components/ship/index.es
views/redux/index.es
views/redux/ui.es
views/tabarea.es

Add new store: ui
```js
{
activeMainTab: 'mainView',
activePluginName: '',
activeFleetId: 0,
}
```
Render cost: about 30ms -> 50ms
Please comment if have any question

Reduxify Tabarea

---

.travis.yml
appveyor.yml
package.json

So it will be painful for anyone who want to add new rules, lol

add eslint to ci

---

assets/css/app.css
i18n/others/en-US.json
i18n/others/ja-JP.json
i18n/others/ko-KR.json
i18n/others/zh-CN.json
i18n/others/zh-TW.json
views/components/info/map-reminder.es
views/redux/sortie/index.es

- add sortie resource at current node and in history in `sortie` store
- show total resource commit during sortie in mini map reminder
- minor improvement on map reminder component

Sortie resource show in mini map reminder

---

README.md
assets/data/plugin.json

adding EZ Exped to plugin list.
no translation available for KO and JP, falling back to EN.

adding EZ Exped to plugin list

---

assets/css/app.css
assets/js/plugin-preload.js
assets/js/webview-preload.js
views/components/info/alert.es
views/components/settings/parts/display-config.es
views/services/layout.es

poi-info now affected by zoom level option,
close https://github.com/poooi/poi/issues/1403
Update: plugin windows are also affected now; ZoomLevel & panelMinSize now is applied after mouseUp or touchEnd event

Zoomed poi-info

---

assets/data/plugin.json

adding starcraft to plugin list

---

assets/css/app.css
i18n/main/ja-JP.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/components/main/parts/admiral-panel.es
views/components/main/parts/countdown-timer.es
views/components/ship-parts/topalert.es
views/components/ship/assets/ship.css

ref #1416 
Refactor admiral panel, and add countdown tooltip for
- Practice
- Quest
- Senka
- EO

Add countdown timer

---

assets/css/app.css
views/components/info/alert.es

Fixes https://github.com/poooi/poi/issues/1423

Use an alternative method toggling poi-alert

---

assets/data/plugin.json

was #1478. making a new branch for a clear patch.

adding poi-plugin-leveling to list

---

views/redux/const.es
views/redux/info/index.es
views/redux/info/presets.es

- const.$exslotEquips
- const.$exslotEquipShips
- info.presets

add new state:

---

assets/css/app.css
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/others.es

Add app performance monitor

---

views/app.es

Fixes #1505 and lost menu on macOS.
More details [here](https://github.com/poooi/poi/commit/684d387b99ab30736541a52ecc3063ea9ae2db8b#diff-d689967879cf822796c892c660570440)

Fixes #1505 & re-enable menu on macOS

---

assets/css/app.css

Add Chinese Fonts for Windows Menu

---

views/components/etc/menu.es

No command key for Windows/Linux

---

assets/js/webview-preload.js
package-lock.json
package.json
views/components/settings/parts/plugin-config.es
views/services/plugin-manager-utils.es
views/services/plugin-manager.es

Delay & Asynchronize plugin load process

Better plugin load

---

views/redux/ui.es
views/tabarea.es

introducing `autoSwitch` in `@@TabSwitch` action to make it possible to
distiguish user action from those made automatically.

`autoSwitch` flag in `@@TabSwitch`

---

views/env-parts/data-resolver.es
views/redux/info/index.es
views/redux/info/server.es

make available server info in redux store

make available server info in redux store

---

i18n/main/en-US.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/components/main/parts/expedition-panel.es

Expedition panel now shows fleet status

---

assets/data/plugin.json

as title says, proved useful enough to get listed.

adding mo2 (morale monitor) to plugin list

---

app.js
appveyor.yml
build-detail.es
package-lock.json
package.json
views/components/settings/display/theme-config.es
views/env-parts/theme.es

Use undocumented API `SetWindowCompositionAttribute`. Can be unavailable in the future.

Add vibrancy to Windows version

---

lib/ipc.es
views/create-store.es
views/redux/index.es
views/redux/ipc.es
views/utils/selectors.es

add `ipc` store so that caller don't have to check service availability with each call

feat: Reduxify inter plugin call module

---

assets/data/quest_goal.cson

Tracking quarterly quest "近海に侵入する敵潜を制圧せよ！"

Tracking quest 428

---

assets/css/app.css
views/components/etc/menu.es
views/components/info/alert.es
views/components/info/toastr.es
views/components/main/index.es
views/components/main/parts/miniship.es
views/components/settings/index.es
views/components/ship/index.es
views/env-parts/theme.es
views/services/layout.es

Use import css syntax in js like css-loader by hacking require.

CSS loader kakko kari

---

views/redux/info/fleets.es

as title says, added handling for `api_req_member/updatedeckname`

update fleet name as soon as user has changed it in game

---

assets/data/constant.cson
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/assets/settings.css
views/components/settings/misc/fcd.es
views/components/settings/misc/index.es
views/components/settings/misc/wctf-db.es
views/create-store.es
views/redux/fcd.es
views/redux/index.es
views/redux/wctf.es
views/utils/selectors.es

Who Calls The Fleet database (wctf-db) could provide us:
-  extra ship info to help in calculating evasion, LoS and ASW, which is impossible to retrieve from API data with new equipment bonus mechanism (Tanaka directly modifies API data)
- item improvement data
- ship classification data
The database's installation and update process is similar to that of plugin, and we'll load data into redux store and enable its persistence

Add Who Calls The Fleet database

---

views/create-store.es

combine some `observe` calls into one in `create-store.es`.

combine some observe calls into one

---

views/components/etc/icon.es

- using memoize instead of Object-based caching mechanism
- simplified & improved registering: let iconConf assign a key instead of allowing client to create one.
- and some syntactic simplifications.
tested locally.

simplify icon implementation

---

docs/plugin-cn.md
docs/plugin.md

I found two description mistake when I read the plugin.md
1.  `export funtion pluginWillUnload()` -> `export function pluginWillUnload()`
2.  the `typeof footer` in `window.toggleModal` should be `array`

maybe there are two description mistake in the plugin.md file

---

views/services.es
views/services/utils.es

Just unifying some `F5` related actions to use existing functions to `views/services/utils`.

unify code for refreshing

---

.stylelintrc.js
assets/css/app.css
assets/css/global.css
package-lock.json
package.json
views/components/etc/assets/avatar.css
views/components/info/assets/alert.css
views/components/info/assets/control.css
views/components/info/assets/map-reminder.css
views/components/info/assets/toast-animate.css
views/components/info/assets/toast.css
views/components/main/assets/admiral-panel.css
views/components/main/assets/expedition-panel.css
views/components/main/assets/main.css
views/components/main/assets/miniship.css
views/components/main/assets/resource-panel.css
views/components/main/assets/task-panel.css
views/components/settings/assets/misc.css
views/components/settings/assets/navigator-bar.css
views/components/settings/assets/plugins.css
views/components/settings/assets/settings.css
views/components/ship/assets/ship-item.css
views/components/ship/assets/ship.css
views/components/ship/assets/slotitems.css

Stylelint provides a more extensive and yet configurable rule set

Replace CSSLint with Stylelint

---

i18n/menu/en-US.json
i18n/menu/ja-JP.json
i18n/menu/zh-CN.json
i18n/menu/zh-TW.json
views/components/etc/menu.es
views/components/settings/display/zooming-config.es

- now set `poi.window.height` & `poi.window.width` can work immediately.
- need i18n `ko` & `jp` translation.

feat: add reset-views in menu

---

views/utils/selectors.es

adding a selector that maintains ships' remodel chains, which could be useful for various purposes.
see comments in patch for details.

adding remodel chains selector

---

assets/css/app.css
views/components/settings/assets/settings.css
views/components/settings/display/layout-config.es
views/components/settings/display/theme-config.es
views/poi-app.es
views/services/layout.es

A new layout for users who has a small screen.
The information panel is hidden unless triggered by user to save screen space.

feat: add overlay panel layout

---

views/components/info/control.es

TL;DR: Working implementation of screenshot capturing using the canvas, the relatively new APIs "captureStream" and "ImageCapture", and Inter-plugin-communication.
Implementation was partially inspired by #1909 and the commit cc7773706c2e208257259555c343b5397470746d
----
A bit of the background information: I use a High-DPI screen (2880x1920 on a 10.1" monitor, ~342ppi) and must set Window's display scaling to 200% to use properly.
Because of this, whenever launch poi it would be upscaled by 200%. Everything looks right and the UI is as usable as not scaled.
However, screenshots looks bad and the resolution it uses is weird.
For example, when I use poi at 100% scaling, the resolution poi thinks I'm using is 1200x720. The actual rendered resolution is 2400x1440 due to the 200% scaling by …

Capture screenshots with Canvas and capture stream.

---

views/utils/aapb.es

luck contribution should be of x0.9 *see comments in CL

chore: update AAPB formula

---

assets/js/webview-preload.js

Automatically change date to current date + 1 year.
Fixes cookie hack being broken since today

Update cookie hack

---

views/utils/aaci.es

fix: ise k2 aaci kind 28

---

app.js
lib/__tests__/__snapshots__/utils.sepc.es.snap
lib/utils.es

Since poi is not built for multiple account usage, it is better to allow only one running instance to prevent unexpected cache loss

Allow only one running instance

---

views/utils/game-utils.es

Reference: https://wikiwiki.jp/kancolle/二式陸上偵察機

feat: tyku bonus from land-based reconnaissance aircraft

---

i18n/main/en-US.json
i18n/main/ja-JP.json
i18n/main/ko-KR.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/redux/info/equips.es
views/redux/info/quests.es
views/services/development-prophecy.es

There is a [change](https://github.com/andanteyk/ElectronicObserver/commit/c350f89dbc56aabf5a218fa7f5b2b6972897ab5d#diff-0254e2c984ffce7483ba83340a3fe255) in development API, it is possible to craft either one or three pieces of equipment now.
```json
{
"api_create_flag": 0,
"api_material": [1101, 1002, 916, 1100, 5, 4, 1, 0],
"api_get_items": [{ "api_id": -1, "api_slotitem_id": -1 }],
"api_unset_items": null
}
```
```json
{
"api_create_flag": 1,
"api_material": [1081, 962, 856, 1080, 5, 4, 0, 0],
"api_get_items": [{ "api_id": 18, "api_slotitem_id": 2 }],
"api_unset_items": [{ "api_type3": 1, "api_slot_list": [17, 18, 10] }]
}
```
```json
{
"api_create_flag": 0,
"api_material": [1071, 1032, 997, 1070, 5, 4, 4, 0],
"api_get_items": [
{ "api_id": -1, "api_slotitem_id": -1 },
{ "api_id": -1, …
```

Update api_req_kousyou/createitem handling

---

commitlint.config.js
package-lock.json
package.json

I see no value out of this format enforcement
other than some false sensation of feeling commits being more organized.

drop commitlinit completely.

---

views/utils/aaci.es

Fix CDMG predicate.

---

i18n/main/en-US.json
i18n/main/ja-JP.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/components/ship/index.es
views/components/ship/ship-item.es
views/redux/sortie/index.es
views/utils/sp_attack.es

close https://github.com/poooi/poi/issues/2082

feat: add sp attack indicator

---

views/kan-game-wrapper.es

close https://github.com/poooi/poi/issues/2246
A weird workaround to fix a weird upstream issue

fix: a workaround for audioMuted issue

---

views/redux/info/ships.es

Added handling of kcsapi/api_req_kaisou/open_exslot,
which is responsible for opening the extra slot.
Tested on my fleet.

Handle slot open events.

---

views/utils/game-utils.es

- fix bonus of 陸偵
- fighter power of 陸偵 should be added when landbaseStatus is 1

Fix calculation of fighter power of land base

---

i18n/others/ja-JP.json
i18n/others/ko-KR.json
i18n/others/zh-CN.json
i18n/others/zh-TW.json
views/services/modernization-delta.es

1. 未计算对潜和耐久的最大值（不知道怎么算）
2. 没怎么实际测试（因为手上没海防了）
求砍口垒大佬来肉测（躺）

近代化改修显示对潜和耐久 (See #1593)

---

.gitignore
app.js
i18n/others/en-US.json
lib/flash.es
views/redux/info/quests.es
views/services/utils.es

Now he has no job other than to show WARNING on startup.
It's time to say goodbye.

refactor: farewell to flash wreckage

---

views/utils/aaci.es

Or Town-class in general. Pre-remodel form not tested but it should be
a fair assumption.

HMS AACI support for Shelffield.

---

views/components/info/control.es

Not yet tested - openning a PR optimistically.

0-padding timestamp in screenshots

---

assets/data/plugin.json

The old plugin is too difficult to maintain and has given up.
Thanks [kcanotify-gamedata](https://github.com/antest1/kcanotify-gamedata) for maintaining [plugin-quest-2](https://github.com/lawvs/poi-plugin-quest-2) data.

chore: add poi-plugin-quest-info-2 recommendation

---

assets/data/plugin.json

Thanks kcwiki

---

views/utils/aapb.es

AA gun actually has a better triggering rate with AA stat >= 8, per wikiwiki article.

Improve AAPB activate rate formula.

---

views/components/settings/plugin/plugin-item.es

For more detail, see https://github.com/jonschlinkert/remarkable/issues/171

Fix markdown link

---

views/redux/actions.ts
views/redux/info/airbase.ts

Provide redux update to `info.airbase` for kcsapi `api_req_air_corps/change_deployment_base`. Test manually.

Support swapping airplanes between squardons

---

views/utils/game-utils.es

chore: update function equipIsAircraft
