poooi/poi

views/components/main/parts/task-panel.cjsx

Fix a bug that can cause error when the current quest page is empty

Fix a task-panel bug

---

views/components/settings/parts/poi-config.cjsx

It seems that it cannot select both "Cache" and "Pepper Data" folders, so I choose to select **"Cache"** folder.Because the other folder is not always exist.

Select item when open the cache dir

---

assets/css/app.css
assets/css/layout.horizonal.css
views/app.cjsx
views/components/settings/parts/poi-config.cjsx
views/double-tabareas.cjsx
views/env.coffee
views/single-tabarea.cjsx

This pr adds a option to open tabbed layout. It means that you can see game, components, plugins views at the same time. Hot keys are changed to
+ Cmd/Ctrl + Tab: Next component
+ Tab: Next plugin
+ Shift + Tab: Last plugin

Add double tabbed layout

---

app.coffee
lib/shortcut.coffee

This pr adds a shortcut to hide/restore windows quickly.
Config interface:
path: poi.shortcut.bosskey
type: [Electron Accelerator](https://github.com/atom/electron/blob/master/docs/api/accelerator.md)
default: 'CmdOrCtrl+p+o+i'

Add shortcut to hide and restore

---

views/env.coffee

It saves the "/start2" api's body in localStorage, so when 'env' is required, some global variables (starting from $) can be initialized without waiting for "/start2" api.
This change can help to slove new-window-plugin crashed problem. Crashed plugins can recreate itselves during the game.

Add variable init

---

gulpfile.coffee

See here #188 
Force redownload the PepperFlash, even if there is the file of the same name
Win 10 x64 Pro works well.

Force redownload PepperFlash

---

views/components/main/assets/main.css

之前
之后
原因：
`main.css` L33 `text-align: right;` 被应用到 task-panel 中

Fix: task-panel align to right

---

index.html

On OSX, the copy/paste shortcuts don't work because of the missing menu. According to the contributor's hint in https://github.com/atom/electron/issues/2402, I added the native menus in [index.html](../blob/master/index.html). It works well on v3.2.1.
I also added some other menu items and shortcuts for convenience, like minimize, reload and stop.
This commit shouldn't affect the Windows and Linux version.

Add native menus on OSX and Fix #55

---

assets/css/app.css

在不同主题中 `poi-info` 的高度不同，
如 darkly 中为 `30px`、paperdark 中为 `28px`。
然而在 `app.css` 指定了 `poi-control` 的高度为 `28px`，这并不合适。
删掉指定高度的 css 可以在不同主题下自动适应高度。

修复 poi-control 在某些主题下高度错误

---

app.coffee

Would fix the issue on some buggy http proxies that do not support SSL. Fixes #370
Require <a herf= "https://github.com/atom/electron/releases/tag/v0.33.2">Electron v0.33.2</a> or higher

Limiting minimum SSL fallback version to TLS1.0

---

views/components/main/parts/miniship-parts/minipanebody.cjsx

欧选的高压锅（
To reproduce:
1. 捞条新船
2. 切换到expanded ship view
3. 把新船编入舰队
4. 然后概览面板就挂啦
cc @KochiyaOcean

Fixed: ship pane stuck under certain situation

---

lib/proxy.coffee
lib/utils.coffee
views/app.cjsx

1. EXROOT now is
win32: execPath
linux / darwin: appPath
2. Cache is only valid in EXROOT
win32: EXROOT/cache
linux / darwin: EXROOT/MyCache
3. `mainD2.swf` is cached now.

Proxy and Cache modification

---

views/layout.horizontal.cjsx
views/layout.vertical.cjsx

移除了自动适配时height的-1，win8.1 + electron 0.34.1 没出现多余的白边。
之前不加-1的时候会出现白边，现在好像已经没这个问题了？
需要更多平台的测试。

Fix game-webview size

---

app.coffee
docs/plugin-cn.md
views/components/settings/parts/navigator-bar.cjsx
views/layout.cjsx
views/layout.horizontal.cjsx
views/layout.vertical.cjsx

The latest Electron has deprecated The “Url” in API names.
https://github.com/atom/electron/releases/tag/v0.35.0
_**All the plugins should be updated as well, at the time this pr is merged.**_

Updates for Electron v0.35.0

---

views/components/main/parts/miniship.cjsx

#600 
Currently the only way to locate the miniship panel when it displayes as component of main tab, is `#MiniShip > div > div:nth-child(1)`.This PR is to make it easy to differentiate the appearence of miniship panel whether it is expanded or not.
Below is the effect I want to realize:
I'm not sure if the id name is in a poi-like style

add an id for miniship when it displays as component of main tab

---

views/app.cjsx

Blur the webview when Command key is pressed on Mac, so the shortcuts won't be eaten by flash.

Made MacOSX shortcuts always work

---

assets/css/app.css
views/single-tabarea.cjsx

The plugin nav item is split into 2 sub items, one for selecting plugins, one for quickly return to last selected in-app plugin.
unsolved:
- settings component displayname
- key for new item
unknown:
- can this handler cover all cases?

Tentative plugin tab redesign for #706 

---

i18n/setting/en-US.json
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/display-config.cjsx

- Change the checkbox "Use fixed resolution" to the opposite ("Use adaptive resolution") to make it clearer.
- Allow non-standard percentage shown in resolution。
- Extracted DisplayConfig into separate parts.
- Add rounding to numbers.
- Other fixes.

Display config refactoring

---

views/components/settings/parts/display-config.cjsx

The cap is determined by the layout.
When the width requested exceeds the cap, the maximum possible width is used.

Add max resolution cap.

---

views/components/main/parts/teitoku-panel.cjsx

解决军衔不更新的问题，并且符合每次回母港刷新所有数据的惯例。
减少了重复的代码。
目前还在测试中，不过应该没什么问题。理论上唯一变动的地方就是收到 port 包的处理。

update api basic on port

---

lib/cl.coffee

It might be an arg for electron/node/chrome...
-> #922

Remove the 'invalid argument' warning

---

views/redux/index.es

These `{}` bring extra 90-500 ms CPU time for actions that shouldn't have changed store (ie. ` @@Request`).

Fixed: empty object

---

assets/data/plugin.json
package.json
views/components/settings/assets/settings.css
views/components/settings/parts/plugin-config.es

- Use react-markdown to show links in plugin description.
- Links are colored as light blue by css. Can change that (either color or underline) if necessary.
- Review the descriptions if you can.
- Descriptions also need updating in each plugin repo.

Use markdown for plugin description. Update plugin description.

---

views/redux/info/airbase.es

Adds support for `/kcsapi/api_req_air_corps/` API to update the airbase at correct index.
The info.airbase store structure is same as `/kcsapi/api_get_member/mapinfo`, which is an array of all bases. 
Event area airbases will be appended to those of Area-6. During event, the API postBody's `api_base_id` key might not be the index at airbase array, resulting improper updates. This PR will fix this via `api_base_id` and `api_area_id` matching.

event airbase support

---

i18n/main/en-US.json
i18n/main/ja-JP.json
i18n/main/ko-KR.json
i18n/main/zh-CN.json
i18n/main/zh-TW.json
views/components/ship-parts/topalert.es
views/utils/game-utils.es

With a cleaner commit history this time:innocent:
Implemented #1004

Add FP without aircraft proficiency and remodel level bonus

---

i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/plugin-config.es
views/services/plugin-manager-utils.es

Plugins will be kept latest on main poi startup. The feature is disabled by default and can be enabled on plugin config panel
closes #1332

Add auto update plugins feature

---

app.js
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
lib/cl.es
views/components/settings/parts/plugin-config.es
views/components/settings/parts/poi-config.es
views/create-store.es
views/env.es
views/services/plugin-manager.es

If provided in command line option `--safe` or `-S` or checked `enter safe mode on next startup` in config panel, poi will enter safe mode with all plugins not enabled, and the store will be clear. The config check will be reset.
A panel will display for plugin config panel in safe mode:
closes #1233

Add safe mode feature

---

views/redux/info/maps.es

Map HP update for event map rank changes happens in `@@Response/kcsapi/api_req_map/start`, but some plugins such as `where my fuels gone` may read the value before, resulting incorrect map hp records in the plugin
This patch adds another update directly with `@@Response/kcsapi/api_req_map/select_eventmap_rank`

update maphp when selecting event map rank

---

i18n/others/en-US.json
i18n/others/ja-JP.json
i18n/others/ko-KR.json
i18n/others/zh-CN.json
i18n/others/zh-TW.json
views/components/info/control.es
views/components/settings/parts/navigator-bar.es
views/components/settings/parts/poi-config.es
views/services/utils.es

Adding a refresh button on control bar:
- interactions:
- Click: Opens a dialog that user can choose between "Refresh page" or "Reload Flash"
- Shift+Click: Refresh page
- Right Click: Reload Flash
- togglable through common setting page
- boolean setting located at `config.poi.showControlBarRefresh`,
`false` by default.
- ~~it's possible to merge this feature completely into https://github.com/poooi/plugin-prophet which might require main app to provide a way of inserting buttons into the control bar~~ (cancelled due to probably unnecessary complication)
- ~~a planned future improvement is to allow fine-grained control of whether to enable this function depending on branch prediction (e.g. allow user to specify things like "when triggered, allow refresh on 2-2A, but do nothing on any …

Adding a refresh button on control bar

---

docs/style-guide.md

Oh my Kagami, thank you for these wonderful guides and documents!
I definitely appreciate your effort for such great work!
I happen to see there are a few errors in the English one and correct them as I look through. This pull request is in an attempt to make the document even better.
* Code should always be code in the sense of programming. [source](http://english.stackexchange.com/questions/20455/is-it-wrong-to-use-the-word-codes-in-a-programming-context)
* I change all esLint or eslint to ESLint since it brand itself as so? I excluded SublimeLinter-eslint due to their branding of the plugin is lowercase. 
* There are some other minor mistake corrections in this pull request such as spelling and grammar.

Doc/ Enhance English Style Guide

---

i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/parts/poi-config.es
views/tabarea.es

Plugin add a new option: `switchPluginPath`
`switchPluginPath` is a array includes api path when should switch to the plugin.
example:
```js
export const switchPluginPath = [
'/kcsapi/api_req_map/start',
'/kcsapi/api_req_practice/battle',
'/kcsapi/api_req_map/next',
]
```
if conflicted, the plugin with higher priority will be chosen.

Add tab-auto-switch function

---

views/tabarea.es

Now two types of `switchPluginPath` is supported
```js
export const switchPluginPath = [
'path1', // switch to plugin when get this api
{
path: 'path2',
valid: function() { ... },
}, // switch to plugin when get this api and valid() return true
]
```

Support valid function

---

app.js
assets/js/plugin-preload.js
views/components/settings/parts/display-config.es
views/env-parts/getter.es
views/redux/layout/index.es
views/services/device-pixel-ratio-detector.es
views/services/layout.es

Use a alternative HiDPI logic:
- Set DPI scale from system setting
- Webview’s size now is affected by `window.devicePixelRatio` to ensure getting actual size for screen
This PR closes #1412 , closes #1408 and closes #1403

Alternative hidpi support

---

lib/shortcut.es
lib/window.es

new window's `webPreferences` is removed, for plugins using Flash player, please explicitly add it in window options @KochiyaOcean

fix window position if it is out of current displays' bounds

---

views/components/info/control.es

change to a non-blocking behavior of opening directories for some quickbar buttons, which allows user to browse the directory while keeping main UI functioning (previously opening a directory blocks UI)

change to a non-blocking behavior of opening directories

---

views/services/plugin-manager.es

- for reloading plugins from devtool console.
- `reloadPlugin(<packageName>[, verbose=false])`
- prefix `poi-plugin-` can be omitted

adding window.reloadPlugin

---

app.js
views/components/etc/menu.es
views/services/layout.es

Since the word resizable implies that this window size is fixed, maximizable and fullscreenable should be considered disabled too
fixes #1497

make resizable == maximizable == fullscreenable

---

app.js
i18n/others/en-US.json
i18n/others/ja-JP.json
i18n/others/ko-KR.json
i18n/others/zh-CN.json
i18n/others/zh-TW.json
index.html
views/app.es
views/utils/http-basic-auth.es

Implemented #1496
When website wants to challenge an http basic auth, a login form will pop out to collect credentials.
If the credential is incorrect, the form will pop out again if the server still accepts login attempt.
Due to the limitation of electron, the cancel behavior will not call back the server with any further information, and the connection will be closed by server if timed out. However a standard browser will try to connect without any auth information instead, which is better for using.
The i18n is not completed yet , some language is using english translation instead

added http basic auth support #1496

---

lib/touchbar.es
views/components/info/control.es

TouchBar inputs are now stateless which:
1. Avoids abusing of <code>config</code>
1. Prevents unnecessary re-rendering
1. Decreases the number of times <code>handleTouchbar()</code> is called by half

Make touchbar input stateless

---

views/components/main/parts/minishipitem.es
views/components/ship-parts/topalert.es
views/components/ship/lbac-view.es
views/utils/game-utils.es

The AP shown on panels currently is the Max FP by default. It works well on most of the situations, but not on the case that there are aircrafts with 0 proficiency level. A 0-level (no label) aircraft usually means "a new aircraft" or "a totally destroyed squadron", and users may be confused with or even mislead by the larger than expected FP.  
This PR will make the FP shown on panel to exclude the internal proficiency bonus of a 0-level aircraft. The Max and Min FP is still available through the tooltip.

Refine the FP display

---

views/redux/const.es

turns out `api_id` indicates ship master id **after remodeling**. due to having cyclic remodel chains in game, `api_id` is not unique among elements in `api_mst_shipupgrade`.
so I think the best we can do is to keep it intact and let developers using it decide what to do.
the name is still `$shipUpgrades`, as it's easy to distinguish Array from Object and there are no other packages using this except navy album, I think this is not a big problem.
p.s. however `api_current_ship_id` is unique if you take out every  `api_current_ship_id = 0` values. because there is no branched remodeling in game ~~yet~~.

keep $shipUpgrades intact instead of indexifying it

---

views/services/plugin-manager-utils.es

This enables plugins to load new translate strings upon hot restart

disable i18n-2's file cache

---

assets/data/quest_goal.cson
views/redux/info/quests.es

- add quarterly quest record resetting
- add "fuzzy" mode to match multiple requirements of a same type
- add new quests
+ D24 海上通商航路の警戒を厳とせよ 
+ F55 新型艤装の継続研究
+ Bq2 戦果拡張任務！「Z作戦」前段作戦

Quest maintenance

---

lib/shortcut.es
views/components/etc/menu.es
views/services/plugin-manager-utils.es

This PR will use local keyboard shortcut to toggle devtools instead of using global shortcut. 
Fixes #1557.
The legacy global shortcuts is not yet removed and can be reenable by set `poi.shortcut.useGlobalDevToolShortCut` to `true`

Use local shortcuts

---

README.md

to shorten the readme and make opencollective more visible

move screeshot & plugin list to wiki page

---

.travis.yml
appveyor.yml
package-lock.json
package.json

- removed opencollective dependencies because our end users could not notice it.
- avoid npm 5.4.0 permission bug that keeps ci on Linux and macOS failing https://github.com/npm/npm/issues/18324

fix ci npm version

---

views/utils/game-utils.es

As for the effect of improvement, a seaplane fighter gains ★×0.2 AA bonus like a carrier-based fighter.
Source: [改修総合スレッド | 艦これ検証Wiki | FANDOM powered by Wikia](http://ja.kancolle.wikia.com/wiki/%E3%82%B9%E3%83%AC%E3%83%83%E3%83%89:951#42)

Seaplane fighter gains improvement benefits

---

views/redux/const.es

add const.$graphs to store in form of indexified object, going to deprecate const.$shipgraph because it is an Array and in practice the Object form is more favorable.

add const.$graphs

---

i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/settings/plugin/index.es
views/services/plugin-manager.es

This PR introduces a functionality to completely remove and reinstall all plugins. It is considered helpful for solving plugin dependency compat problem for users upgrading from legacy versions.
Added a `window.gracefulResetPlugin()` shortcut to help user completely remove the directory
Minor code changes:
- move loading mirrors and configs to `PluginManager`'s `constructor` part

Feature: reset / repair plugin directory

---

views/services.es

It is found that DMM will redirect requests from US IP with `accept-language` header set as `zh-CN`, but using `en-US` or `ja-JP` is OK

Feat: set accept-language header with DMM cookies enabled

---

assets/data/quest_goal.cson
views/redux/info/quests.es

- update to quest DSL:
originally `slotitemId` (api_type[3]) is used, which actually stands for icon ids,
which makes it inconvenient in some cases
(e.g.  small calibre guns have two different icons, one of them is shared with high-angle mounts
which does not necessarily fall into small calibre category)
instead DSL is modified to use `slotitemType2` (api_type[2]).
Related quests are updated accordingly as well.
- tracking new daily quests (tested locally)

Tracking new quests & update to quest DSL

---

views/create-store.es
views/redux/info/repairs.es
views/redux/info/ships.es

This patch brings in 2 changes:
- docking completion without using instant repair item updates `info.ships` accordingly.
- deal with "instant docking completion". simply put, when docking time is less than 60 seconds,
we cannot detect docking completion by observing changes to `info.repairs`. the solution to this is 
explained in [my comment](https://github.com/Javran/poi/blob/66f66457cc834fc9ab6225e0772dc70e5857cf8a/views/redux/info/ships.es#L5-L45). please check it out for more details.
Fixes https://github.com/Javran/poi-plugin-docking/issues/3

Update docking-related info more closely

---

views/components/ship/oasw-indicator.es
views/utils/oasw.es
views/utils/selectors.es

done and tested (except for cases with type 0 sonar).
the last 2 commits are not necessary, but it attempts to derive the list of CVEs from const data, which is more futureproof and results in less magic ship id. not sure whether it's a good thing or not.

refactor OASW related code

---

assets/js/webview-preload.js

Some DMM ads scripts will call `document.write` after the game page is loaded which clear the entire page and cause "black screen".
It is to prevent `document.write` from running if the page is loaded.

Block document.write after page is loaded to prevent page from being cleared

---

views/components/main/parts/minishipitem.es

Examples:
Some issues:
* Not sure where `levelToExp` should be.
* Only in overview view, can be in fleet view as well.

Add more experience info in ship tooltips

---

i18n/main/en-US.json
views/components/main/parts/minishipitem.es

New version:
`Remodel: ready` for reversible remodels as well (like Shoukaku).

Fix ship-tooltips PR

---

views/components/main/parts/task-panel.es

Instead of importing titles from quest plugin, prefix with wiki ids (same as expeditions) from it and use translator plugin for titles with api id contexts.
without quest plugin will be no wiki id prefixes and no requirement translations, quest titles should be provided via translator plugin.

Fix quest translations in overview

---

views/services/plugin-manager.es

Reseting the isBroken flag on running reloadPlugin allows for easier reloading

Allow for reloading a broken plugin

---

build/utils.es
gulpfile.js

gulp tasks not working on Linux without `sudo` since `/var/local` is only writable by root. Mimicking [`app.getPath('appData')`](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname) so that the right path (`$XDG_CONFIG_HOME/poi` or `~/.config/poi`) is used on Linux as well.

Remove npm mirror selection in gulp

---

README.md

Adding chocolatey install guide in the "UNOFFICIAL releases" section. https://github.com/poooi/poi/issues/1979

(readme) Added poi windows install using chocolatey.

---

app.js
i18n/setting/ja-JP.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
lib/tray.es
views/components/etc/menu.es
views/components/settings/main/advanced-config/index.es
views/env.es

implement macOS tray
other modifications:
- API rename: `appIcon` -> `appTray`
- remove unused linux `show tray icon` setting
closes #2055

macOS Tray

---

views/utils/game-utils.es

As mentioned on Discord. Also removed non-existent (?) equipment types 56 and 58.

fix: 艦攻 improvements don't contribute to air power

---

.prettierignore
views/utils/aaci.es

This PR includes:
- Reorganize definitions in aaci.es so that all item or ship-specific predicates are closer to their first use sites - I find it easier to maintain this way.
- Simplify predicates for builtin HA mount and CDMG according to wikia
- Support for Atlanta / Atlanta Kai AACI
I planned to also update some shotdown & modifier for existing AACIs, but for now wikia and wikiwiki are having too many disagreeing numbers for me to want to look into.

Some AACI updates

---

jest.config.js
package-lock.json
package.json
views/redux/info/__tests__/quests.spec.es
views/redux/info/quests.es

Fixes #2081.
Make our quest quarter agree with the in-game one,
this allows us to fix the issue where quarterly quests are reset
on incorrect time.

Fix in-game quarter definition.

---

lib/proxy.es

Phase 2 introduced `gadget_html5` in addition to (instead of?) `gadget` on `203.104.209.7`.
Right now this can be used to avoid current IP restrictions without VPN/proxy (i.e., by creating `~/.config/poi/MyCache/KanColle/{gadget_html5,kcscontents}`).

Allow caching of gadget_html5 files

---

views/components/info/control.es

Getting tired of clicking adjust after devtool is opened,
therefore some simple hack.
For whatever reason this won't work first time after launch,
but it'll work for consequent opens.

auto-adjust when devtool is opened.

---

views/redux/sortie/index.es

This allows us to sync a bit better with in-game state,
as get_incentive is the first API call after game starts.

Clear sortie state after a reload.

---

lib/proxy.es

There are two problems in [`useCache`](https://github.com/poooi/poi/blob/master/lib/proxy.es#L380) that prevent custom cache  updates from propagating to the browser (without clearing the whole browser cache):
- `if-modified-since` is not being sent, setting `cache-control` to `max-age=0` allows browser and proxy to always communicate changes via `if-modified-since`.
- `new Date(req.headers['if-modified-since']) >= stats.mtime` comparison doesn't always work as `mtime` (`Date`) can have more resolution (that is, subsecond resolution) than parsed `req.headers['if-modified-since']` (up to a second resolution).

Allow custom cache changes to be recognized by the browser

---

lib/proxy.es

To add to https://github.com/poooi/poi/pull/2281, there are also [those](https://github.com/kcwiki/cache/tree/master/html) files, which can be used during maintenance (or ban) times by https://github.com/kcwiki/poi-plugin-let-me-in (currently shows 403 in maintenance).

fix: allow caching /html/ files

---

app.js

This feature is basically useless and a waste of resource - there are only a handful of places that have non-numeric textbox and we either put url or katakana in there that I doubt spell check can produce any sensible result.

Disable spellcheck.

---

views/components/tab-area/index.es

Otherwise plugin pane is empty at start if first plugin happens
to be in window mode.

Only select non-window plugins to display at start.

---

app.js

Introduce a somewhat hidden feature for advanced users: command line arguments can now be extended through `APPDATA/poi/hack/argv.json`. See comments in code for detail explanations.

Provide a way to specify extra command line flags.

---

i18n/setting/en-US.json
i18n/setting/ja-JP.json
i18n/setting/ko-KR.json
i18n/setting/zh-CN.json
i18n/setting/zh-TW.json
views/components/main/parts/mini-ship/mini-ship-pane.es
views/components/settings/display/theme-config.es

This PR adds the configuration under appearance, and default to the current behavior.
When disabled, the overview panel will display the same detailed information as the fleet panel, which include equipment information and fleet stats summary, etc.
Agreed how it looks depends on the screen space, but hopefully leaving it as a configuration it's not too bad

Add option to display detailed information in overview

---

views/utils/selectors.es

`const maxCount = $map.api_required_defeat_count` 改为 `const maxCount = map.api_required_defeat_count`
‘@@Response/kcsapi/api_start2/getData’ --> api_mst_mapinfo 中的 api_required_defeat_count 固定为第一阶段的击破次数
‘@@Response/kcsapi/api_get_member/mapinfo’ --> api_map_info 中的 api_required_defeat_count 会随着阶段改变而改变
`const nowCount = map.api_defeat_count || maxCount` 改为 `const nowCount = map.api_defeat_count ?? maxCount`
当 map.api_defeat_count 值为 0 时会误判而不显示海域血量条

fix: 通常海域多段MapHp显示不正确

---

views/services/alert.ts

`{dontReserve: true}` is not actually being applied in many cases as it's not passed down properly (see diffs).
Tested manually

Fix non-sticky alerts in notification area
